# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Baltig < Formula
  desc "GitLab pipeline TUI"
  homepage "https://github.com/benly50s/baltig"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/benly50s/baltig/releases/download/v0.1.2/baltig_darwin_amd64.tar.gz"
      sha256 "35ae185f9cfe1359605e0cfc4de8e453a8a9c2973d0d031be2b661d8ba1cd947"

      define_method(:install) do
        bin.install "baltig"
        bash_completion.install "completions/baltig.bash" => "baltig"
        zsh_completion.install "completions/_baltig" => "_baltig"
        fish_completion.install "completions/baltig.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/benly50s/baltig/releases/download/v0.1.2/baltig_darwin_arm64.tar.gz"
      sha256 "7627da2a82fafff07e69385f9c32401434d424de227b1ade0f5d42860ac77472"

      define_method(:install) do
        bin.install "baltig"
        bash_completion.install "completions/baltig.bash" => "baltig"
        zsh_completion.install "completions/_baltig" => "_baltig"
        fish_completion.install "completions/baltig.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/benly50s/baltig/releases/download/v0.1.2/baltig_linux_amd64.tar.gz"
      sha256 "020c267fabf1cdb0a289cedce1e4e48de24f8cbcb18f0515d3453ec4c053df12"
      define_method(:install) do
        bin.install "baltig"
        bash_completion.install "completions/baltig.bash" => "baltig"
        zsh_completion.install "completions/_baltig" => "_baltig"
        fish_completion.install "completions/baltig.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benly50s/baltig/releases/download/v0.1.2/baltig_linux_arm64.tar.gz"
      sha256 "26d9f3794a09c39fbe0d8e6a53bd95073c424895cbb8d68ef4e2e6ecac415467"
      define_method(:install) do
        bin.install "baltig"
        bash_completion.install "completions/baltig.bash" => "baltig"
        zsh_completion.install "completions/_baltig" => "_baltig"
        fish_completion.install "completions/baltig.fish"
      end
    end
  end

  test do
    system "#{bin}/baltig --help"
  end
end
