# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Baltig < Formula
  desc "GitLab pipeline TUI"
  homepage "https://github.com/benly50s/baltig"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/benly50s/baltig/releases/download/v0.1.0/baltig_darwin_amd64.tar.gz"
      sha256 "07decf31931fb03f36a5a411b01bfb945f326d6d3ca3fda3bfccb715bef23d98"

      define_method(:install) do
        bin.install "baltig"
        bash_completion.install "completions/baltig.bash" => "baltig"
        zsh_completion.install "completions/_baltig" => "_baltig"
        fish_completion.install "completions/baltig.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/benly50s/baltig/releases/download/v0.1.0/baltig_darwin_arm64.tar.gz"
      sha256 "593050b987d85a9cc8b9b232a769d41dc553e76515c01b57acd1cbf4b766e5d7"

      define_method(:install) do
        bin.install "baltig"
        bash_completion.install "completions/baltig.bash" => "baltig"
        zsh_completion.install "completions/_baltig" => "_baltig"
        fish_completion.install "completions/baltig.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/benly50s/baltig/releases/download/v0.1.0/baltig_linux_amd64.tar.gz"
      sha256 "16b7f971609be2e653408839dc836ad53e2d476f728ba8b7628df95fff863872"
      define_method(:install) do
        bin.install "baltig"
        bash_completion.install "completions/baltig.bash" => "baltig"
        zsh_completion.install "completions/_baltig" => "_baltig"
        fish_completion.install "completions/baltig.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benly50s/baltig/releases/download/v0.1.0/baltig_linux_arm64.tar.gz"
      sha256 "4e24170f7815e729cf28da61cde3e7d027526dbffa870a0b461ce73bb0a0c7b1"
      define_method(:install) do
        bin.install "baltig"
        bash_completion.install "completions/baltig.bash" => "baltig"
        zsh_completion.install "completions/_baltig" => "_baltig"
        fish_completion.install "completions/baltig.fish"
      end
    end
  end

  test do
    system "#{bin}/baltig --help"
  end
end
