# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Baltig < Formula
  desc "GitLab pipeline TUI"
  homepage "https://github.com/benly50s/baltig"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/benly50s/baltig/releases/download/v0.1.1/baltig_darwin_amd64.tar.gz"
      sha256 "d5cc21ebb7585eddd96dabcb0210fc33b69e3460c5d62dd6e5d88945423ae280"

      define_method(:install) do
        bin.install "baltig"
        bash_completion.install "completions/baltig.bash" => "baltig"
        zsh_completion.install "completions/_baltig" => "_baltig"
        fish_completion.install "completions/baltig.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/benly50s/baltig/releases/download/v0.1.1/baltig_darwin_arm64.tar.gz"
      sha256 "b99ef55168a1cb4e299db7eab961f19a23acdbd21a9e611d26482e85872ee69d"

      define_method(:install) do
        bin.install "baltig"
        bash_completion.install "completions/baltig.bash" => "baltig"
        zsh_completion.install "completions/_baltig" => "_baltig"
        fish_completion.install "completions/baltig.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/benly50s/baltig/releases/download/v0.1.1/baltig_linux_amd64.tar.gz"
      sha256 "d2b313f3d28fb03a8db812ac87e1024817de608dc089959dd22a8a41c2b0a3ac"
      define_method(:install) do
        bin.install "baltig"
        bash_completion.install "completions/baltig.bash" => "baltig"
        zsh_completion.install "completions/_baltig" => "_baltig"
        fish_completion.install "completions/baltig.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benly50s/baltig/releases/download/v0.1.1/baltig_linux_arm64.tar.gz"
      sha256 "6a0b8669c1e75ecbb72f1d328502b803046c0347f0d19bbbe581cbdfe11cfc1a"
      define_method(:install) do
        bin.install "baltig"
        bash_completion.install "completions/baltig.bash" => "baltig"
        zsh_completion.install "completions/_baltig" => "_baltig"
        fish_completion.install "completions/baltig.fish"
      end
    end
  end

  test do
    system "#{bin}/baltig --help"
  end
end
