# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K10s < Formula
  desc "Benly's Kubernetes Cluster Manager with TUI"
  homepage "https://github.com/benly50s/k10s"
  version "0.1.14"
  license "MIT"

  depends_on "k9s"
  depends_on "kubelogin"
  depends_on "kubernetes-cli" => :optional
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/benly50s/k10s/releases/download/v0.1.14/k10s_Darwin_arm64.tar.gz"
    sha256 "38d2ec5c777083b7e621f7471eec26a862b5c6d59cbb5c30a7b087cbba8435c4"

    define_method(:install) do
      bin.install "k10s"
      bash_completion.install "completions/k10s.bash" => "k10s"
      zsh_completion.install "completions/k10s.zsh" => "_k10s"
      fish_completion.install "completions/k10s.fish"
    end
  end

  test do
    system "#{bin}/k10s --help"
  end
end
